# Configuration for the Release Drafter workflow
name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
change-template: '* $TITLE (#$NUMBER)'
categories:
  - title: 'New functions/classes:'
    label: 'feature'
  - title: 'Enhancements:'
    label: 'enhancement'
  - title: 'Bug fixes:'
    label: 'bug'
  - title: 'Deprecations:'
    label: 'deprecation'
  - title: 'Backwards incompatible:'
    label: 'breaking change'
  - title: 'Documentation:'
    label: 'documentation'
  - title: 'Maintenance:'
    label: 'maintenance'
exclude-labels:
  - 'skip-changelog'
template: |
  [![DOI](https://zenodo.org/badge/DOI/PASTE_DOI_HERE.svg)](https://doi.org/PASTE_DOI_HERE)

  ## Highlights:

  * DELETE IF THERE ARE NO HIGHLIGHTS

  $CHANGES

  **This release contains contributions from:** $CONTRIBUTORS
